remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: richard jamieson
description: Highly adaptable DeFi specialist and Smart Contract Developer with over 4 years experience in software development and product work in DeFi startups, and prior experience in finance, entrepreneurship, and leadership consulting / coaching. Excellent reputation for collaborating in startup environments to solve problems and ship code.
